# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f405d1f9f6a754631517f0cec839ed23862ad4cebcef8c0fc2013f704e90959a734bd6cd6475c9669a3183882bd85329ccba35abcf85ed1b6cf8ed81920915

test:
  secret_key_base: 60d56b2cadd79dd873328fa3ae63d805fb38294bb02a0790af86f4ef245c129287b64276d72004d621ed705f32c0133103a1d310139398e1e7e4511cb1f913b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
